/**
 * Tests for the V1 routine spec validator. Covers:
 *
 *   1. The two reference routines from the V1 plan (sections 4.2 and 4.4)
 *      validate clean — daily-briefing and inbox-triager.
 *   2. Three malformed specs fail with clear, location-pointing errors:
 *      - step missing required `id`
 *      - step with unknown discriminator `type`
 *      - webhook trigger missing required `secret_env`
 *
 * Fixtures are inline-as-objects rather than YAML-then-parse to keep the
 * protocol package free of a yaml runtime dependency. The structure is the
 * canonical post-parse shape; this is also what the runner will see.
 */

import { describe, expect, test } from "bun:test";

import type { RoutineSpec } from "./index.ts";
import { validateRoutineSpec } from "./validate.ts";

// ─── reference: daily-briefing (V1 plan §4.2) ──────────────────────────────

const dailyBriefing: RoutineSpec = {
	name: "daily-briefing",
	description: "Every morning, summarize yesterday's deck activity into a fresh inbox capture",
	trigger: [
		{ cron: "0 7 * * *" },
		{ webhook: { path: "/hooks/daily-briefing-manual", secret_env: "BRIEFING_SECRET" } },
	],
	concurrency: "skip",
	timezone: "America/Chicago",
	budget: { max_duration_secs: 120, max_llm_cost_usd: 0.05 },
	state: { declared_keys: ["last_briefing_date"] },
	tags: ["daily", "morning", "briefing"],
	steps: [
		{
			id: "should_run",
			type: "transform",
			body:
				"const today = new Date().toISOString().slice(0, 10);\nreturn context.state.last_briefing_date !== today;",
		},
		{
			id: "fetch_completed",
			type: "http",
			when: "steps.should_run.json === true",
			method: "GET",
			url: "http://localhost:8787/api/tasks?state=done&since=24h",
			expect_json: true,
			timeout_secs: 15,
			on_failure: "abort",
		},
		{
			id: "fetch_active",
			type: "http",
			when: "steps.should_run.json === true",
			method: "GET",
			url: "http://localhost:8787/api/tasks?state=active",
			expect_json: true,
			timeout_secs: 15,
			on_failure: "abort",
		},
		{
			id: "fetch_inbox",
			type: "http",
			when: "steps.should_run.json === true",
			method: "GET",
			url: "http://localhost:8787/api/inbox?since=24h",
			expect_json: true,
			timeout_secs: 15,
			on_failure: "abort",
		},
		{
			id: "fetch_failed_runs",
			type: "http",
			when: "steps.should_run.json === true",
			method: "GET",
			url: "http://localhost:8787/api/routines/runs?since=24h&status=failed",
			expect_json: true,
			timeout_secs: 15,
			on_failure: "continue",
		},
		{
			id: "write_briefing",
			type: "agent",
			when: "steps.should_run.json === true",
			model: "claude-sonnet-4-6",
			timeout_secs: 90,
			prompt:
				"Generate a morning briefing in markdown. Keep it tight - 6 to 10 bullets total.\n\nYesterday's completed tasks ({{ steps.fetch_completed.json.length }}):\n{{ steps.fetch_completed.json }}\n\nActive tasks ({{ steps.fetch_active.json.length }}):\n{{ steps.fetch_active.json }}\n\nFresh inbox items in the last 24h ({{ steps.fetch_inbox.json.length }}):\n{{ steps.fetch_inbox.json }}\n\nFailed routine runs in the last 24h ({{ steps.fetch_failed_runs.json.length }}):\n{{ steps.fetch_failed_runs.json }}\n\nStructure exactly:\n\n## What shipped yesterday\n<2-3 bullets of meaningful completions; skip section if nothing>\n\n## In flight\n<2-3 bullets of active tasks worth surfacing; skip section if none worth flagging>\n\n## Needs attention\n<inbox items or failed routines worth flagging; skip if empty>\n\n## Top focus today\n<exactly 1 bullet - the one thing>\n\nTone: direct, no fluff, no preamble.",
			on_failure: "abort",
		},
		{
			id: "write_to_inbox",
			type: "deck",
			action: "create_inbox_item",
			when: "steps.should_run.json === true",
			kind: "capture",
			title: "Morning briefing - {{ run.date }}",
			source: "routine:daily-briefing",
			body:
				"# Morning briefing - {{ run.date }}\n\n{{ steps.write_briefing.stdout }}\n\n---\n_Generated by routine `daily-briefing` run {{ run.id }}_",
		},
		{
			id: "persist_state",
			type: "set_state",
			when: "steps.should_run.json === true",
			state: { last_briefing_date: "{{ run.date }}" },
		},
	],
};

// ─── reference: inbox-triager (V1 plan §4.4) ───────────────────────────────

const inboxTriager: RoutineSpec = {
	name: "inbox-triager",
	description: "Triage unread Gmail every 15 min; draft urgent replies, file the rest",
	trigger: [
		{ cron: "*/15 9-19 * * 1-5" },
		{ webhook: { path: "/hooks/inbox-triager-manual", secret_env: "INBOX_TRIAGER_SECRET" } },
	],
	concurrency: "cancel-previous",
	timezone: "America/Chicago",
	budget: { max_duration_secs: 240, max_llm_cost_usd: 0.1 },
	state: { declared_keys: ["last_seen_timestamp", "last_run_finished_at", "processed_count_today"] },
	tags: ["email", "triage", "daily"],
	steps: [
		{
			id: "fetch_new",
			type: "mcp",
			server: "google-workspace",
			tool: "gmail_search_messages",
			args: {
				query: "after:{{ state.last_seen_timestamp }} is:unread -label:Triaged",
				max_results: 50,
			},
			timeout_secs: 30,
			on_failure: "abort",
		},
		{
			id: "classify",
			type: "agent",
			when: "steps.fetch_new.json.messages.length > 0",
			model: "claude-sonnet-4-6",
			timeout_secs: 120,
			prompt:
				"Classify each message into urgent | important | fyi | spam | archivable. Be ruthless.\n\nMessages: {{ steps.fetch_new.json.messages }}",
			structured_output: {
				schema: {
					type: "array",
					items: {
						type: "object",
						required: ["message_id", "classification"],
						properties: {
							message_id: { type: "string" },
							classification: { enum: ["urgent", "important", "fyi", "spam", "archivable"] },
							reasoning: { type: "string" },
							draft_reply: { type: "string" },
						},
					},
				},
				strict: true,
			},
			on_failure: "abort",
		},
		{
			id: "apply_actions",
			type: "agent",
			when: "steps.classify.json.length > 0",
			model: "claude-sonnet-4-6",
			mcp_servers_allowed: ["google-workspace"],
			skills_allowed: ["deck-inbox", "telegram-bridge"],
			timeout_secs: 180,
			prompt: "Apply triage actions for each item in {{ steps.classify.json }} using the google-workspace MCP server's Gmail tools.",
			on_failure: "continue",
		},
		{
			id: "persist_state",
			type: "set_state",
			state: {
				last_seen_timestamp: "{{ run.iso_started }}",
				last_run_finished_at: "{{ run.started }}",
				processed_count_today: "{{ steps.fetch_new.json.messages.length }}",
			},
		},
		{
			id: "write_summary",
			type: "write",
			path: "inbox/captures/email-triage-{{ run.date }}.md",
			append: true,
			content:
				"## Run {{ run.id }} - {{ run.started }}\nFetched: {{ steps.fetch_new.json.messages.length }}\nClassified: {{ steps.classify.json.length }}\n---\n",
		},
	],
};

// ─── tests ─────────────────────────────────────────────────────────────────

describe("validateRoutineSpec — accepts plan reference routines", () => {
	test("daily-briefing (V1 plan §4.2) validates clean", () => {
		const result = validateRoutineSpec(dailyBriefing);
		if (!result.valid) {
			console.log("daily-briefing errors:", JSON.stringify(result.errors, null, 2));
		}
		expect(result.valid).toBe(true);
		expect(result.errors).toBeUndefined();
	});

	test("inbox-triager (V1 plan §4.4) validates clean", () => {
		const result = validateRoutineSpec(inboxTriager);
		if (!result.valid) {
			console.log("inbox-triager errors:", JSON.stringify(result.errors, null, 2));
		}
		expect(result.valid).toBe(true);
		expect(result.errors).toBeUndefined();
	});
});

test("deck step variants validate clean", () => {
	const spec: RoutineSpec = {
		name: "deck-step-smoke",
		trigger: [{ manual: {} }],
		steps: [
			{
				id: "capture",
				type: "deck",
				action: "create_inbox_item",
				kind: "capture",
				title: "hello",
				body: "world",
			},
			{
				id: "task",
				type: "deck",
				action: "create_task",
				title: "follow up",
				state_ref: "backlog",
			},
			{
				id: "move",
				type: "deck",
				action: "move_task",
				task_ref: "T-1",
				state_ref: "done",
				index: 0,
			},
			{
				id: "promote",
				type: "deck",
				action: "promote_inbox_item_to_task",
				inbox_ref: "i_123",
				mark_processed: false,
			},
		],
	};
	const result = validateRoutineSpec(spec);
	expect(result.valid).toBe(true);
	expect(result.errors).toBeUndefined();
});

test("deck read variants validate clean", () => {
	const spec: RoutineSpec = {
		name: "deck-read-smoke",
		trigger: [{ manual: {} }],
		steps: [
			{
				id: "list_active_tasks",
				type: "deck",
				action: "list_tasks",
				state_ref: "active",
				since_hours: 24,
				limit: 50,
			},
			{
				id: "list_unfiltered",
				type: "deck",
				action: "list_tasks",
			},
			{
				id: "list_unread_inbox",
				type: "deck",
				action: "list_inbox",
				kind: "email",
				since_hours: 12,
				include_processed: false,
				limit: 100,
			},
			{
				id: "fetch_t1",
				type: "deck",
				action: "get_task",
				task_ref: "T-1",
			},
			{
				id: "fetch_inbox_item",
				type: "deck",
				action: "get_inbox_item",
				inbox_ref: "i_01abcdef",
			},
		],
	};
	const result = validateRoutineSpec(spec);
	if (!result.valid) {
		console.log("deck-read errors:", JSON.stringify(result.errors, null, 2));
	}
	expect(result.valid).toBe(true);
	expect(result.errors).toBeUndefined();
});

test("deck get_task without task_ref is rejected", () => {
	const malformed = {
		name: "missing-ref",
		trigger: [{ manual: {} }],
		steps: [{ id: "x", type: "deck", action: "get_task" }],
	};
	const result = validateRoutineSpec(malformed);
	expect(result.valid).toBe(false);
	const hasMissingRef = result.errors!.some(
		(e) =>
			e.keyword === "required" &&
			(e.params as { missingProperty?: string }).missingProperty === "task_ref",
	);
	expect(hasMissingRef).toBe(true);
});


describe("validateRoutineSpec — rejects malformed specs with clear errors", () => {
	test("step missing required `id` produces a required-keyword error pointing at the offending step", () => {
		const malformed = {
			name: "missing-id",
			trigger: [{ cron: "0 7 * * *" }],
			steps: [
				// missing `id` field
				{ type: "wait", duration_secs: 1 },
			],
		};
		const result = validateRoutineSpec(malformed);
		expect(result.valid).toBe(false);
		expect(result.errors).toBeDefined();
		// At least one error should point at /steps/0 and complain about missing `id`
		const hasIdError = result.errors!.some(
			(e) =>
				e.keyword === "required" &&
				(e.params as { missingProperty?: string }).missingProperty === "id" &&
				e.path.startsWith("/steps/0"),
		);
		expect(hasIdError).toBe(true);
	});

	test("step with unknown discriminator `type` fails the oneOf", () => {
		const malformed = {
			name: "bad-type",
			trigger: [{ cron: "0 7 * * *" }],
			steps: [{ id: "bogus", type: "frobnicate", payload: "irrelevant" }],
		};
		const result = validateRoutineSpec(malformed);
		expect(result.valid).toBe(false);
		expect(result.errors).toBeDefined();
		// oneOf failure produces an error at /steps/0 with keyword="oneOf"
		// (Ajv also emits per-branch sub-errors at /steps/0/allOf/<n>/properties/type/const).
		const hasOneOfError = result.errors!.some(
			(e) => e.keyword === "oneOf" && e.path.startsWith("/steps/0"),
		);
		expect(hasOneOfError).toBe(true);
	});

	test("webhook trigger missing `secret_env` produces required-keyword error", () => {
		const malformed = {
			name: "bad-webhook",
			trigger: [
				{ webhook: { path: "/hooks/x" } }, // missing secret_env
			],
			steps: [{ id: "noop", type: "wait", duration_secs: 1 }],
		};
		const result = validateRoutineSpec(malformed);
		expect(result.valid).toBe(false);
		expect(result.errors).toBeDefined();
		const hasSecretEnvError = result.errors!.some(
			(e) =>
				e.keyword === "required" &&
				(e.params as { missingProperty?: string }).missingProperty === "secret_env",
		);
		expect(hasSecretEnvError).toBe(true);
	});
});

// ─── layout (V2 canvas authoring) ────────────────────────────────────────

describe("validateRoutineSpec — layout (V2 canvas)", () => {
	test("routine without layout still validates (backwards compatible)", () => {
		const result = validateRoutineSpec(dailyBriefing);
		expect(result.valid).toBe(true);
		expect(result.errors).toBeUndefined();
	});

	test("routine with a valid layout block validates", () => {
		const spec: RoutineSpec = {
			...dailyBriefing,
			layout: {
				version: 1,
				nodes: {
					should_run: { x: 280, y: 0 },
					fetch_completed: { x: 280, y: 220 },
					fetch_active: { x: 280, y: 440 },
					fetch_inbox: { x: 280, y: 660 },
					fetch_failed_runs: { x: 280, y: 880 },
					write_briefing: { x: 280, y: 1100, collapsed: false },
					write_to_inbox: { x: 280, y: 1320 },
					persist_state: { x: 280, y: 1540 },
				},
				edges: [
					{ from: "should_run", to: "fetch_completed", kind: "success" },
					{ from: "fetch_completed", to: "write_briefing" },
					{ from: "fetch_active", to: "write_briefing", kind: "manual" },
				],
			},
		};
		const result = validateRoutineSpec(spec);
		if (!result.valid) {
			console.log("layout errors:", JSON.stringify(result.errors, null, 2));
		}
		expect(result.valid).toBe(true);
		expect(result.errors).toBeUndefined();
	});

	test("layout edge referencing a nonexistent step id fails with crossRef error", () => {
		const spec: RoutineSpec = {
			...dailyBriefing,
			layout: {
				version: 1,
				edges: [
					{ from: "should_run", to: "ghost_step", kind: "success" },
				],
			},
		};
		const result = validateRoutineSpec(spec);
		expect(result.valid).toBe(false);
		expect(result.errors).toBeDefined();
		const hasCrossRef = result.errors!.some(
			(e) =>
				e.keyword === "crossRef" &&
				e.path === "/layout/edges/0/to" &&
				(e.params as { missingStepId?: string }).missingStepId === "ghost_step",
		);
		expect(hasCrossRef).toBe(true);
	});

	test("layout.nodes key referencing a nonexistent step id fails with crossRef error", () => {
		const spec: RoutineSpec = {
			...dailyBriefing,
			layout: {
				version: 1,
				nodes: { phantom: { x: 0, y: 0 } },
			},
		};
		const result = validateRoutineSpec(spec);
		expect(result.valid).toBe(false);
		const hasCrossRef = result.errors!.some(
			(e) =>
				e.keyword === "crossRef" &&
				e.path === "/layout/nodes/phantom" &&
				(e.params as { missingStepId?: string }).missingStepId === "phantom",
		);
		expect(hasCrossRef).toBe(true);
	});

	test("layout with version != 1 fails with const error", () => {
		const spec = {
			...dailyBriefing,
			layout: { version: 2 },
		};
		const result = validateRoutineSpec(spec);
		expect(result.valid).toBe(false);
		const hasVersionError = result.errors!.some(
			(e) => e.keyword === "const" && e.path.startsWith("/layout/version"),
		);
		expect(hasVersionError).toBe(true);
	});
});

describe("validateRoutineSpec — step schemas coverage (T6)", () => {
	describe("step-http", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "http-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "http", method: "GET", url: "http://example.com" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "http-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "http",
						method: "POST",
						url: "http://api/{{step.id}}",
						headers: { Authorization: "Bearer token" },
						query: { param: "val" },
						body: '{"foo":"bar"}',
						expect_json: true,
						when: "true",
						on_failure: "continue",
						timeout_secs: 30,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "http-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "http", method: "GET", url: "http://example.com", extra_field: true }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "http-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "http", url: "http://example.com" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-agent", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "agent-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "agent", prompt: "Hello agent" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "agent-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "agent",
						prompt: "Do work",
						model: "claude-sonnet-4-6",
						structured_output: { schema: { type: "object" }, strict: true },
						skills_allowed: ["skill-1"],
						mcp_servers_allowed: ["mcp-1"],
						when: "true",
						on_failure: "abort",
						timeout_secs: 120,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "agent-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "agent", prompt: "Do work", invalid_prop: "bad" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "agent-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "agent" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-mcp", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "mcp-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "mcp", server: "srv1", tool: "tool1" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "mcp-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "mcp",
						server: "srv1",
						tool: "tool1",
						args: { arg1: "val1" },
						when: "true",
						on_failure: "retry",
						retry: { times: 3, backoff: "exponential" },
						timeout_secs: 45,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "mcp-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "mcp", server: "srv1", tool: "tool1", unknown_prop: 123 }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "mcp-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "mcp", server: "srv1" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-transform", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "transform-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "transform", body: "return 42;" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "transform-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "transform",
						body: "return context.steps.prev.json;",
						when: "true",
						on_failure: "continue",
						timeout_secs: 10,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "transform-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "transform", body: "return 42;", unknown_attr: true }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "transform-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "transform" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-set-state", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "set-state-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "set_state", state: { key: "val" } }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "set-state-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "set_state",
						state: { key: "val", count: "10" },
						when: "true",
						on_failure: "abort",
						timeout_secs: 5,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "set-state-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "set_state", state: { key: "val" }, extra: "bad" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "set-state-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "set_state" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-write", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "write-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "write", path: "out.txt", content: "hello" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "write-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "write",
						path: "logs/app.log",
						content: "log line\n",
						append: true,
						when: "true",
						on_failure: "continue",
						timeout_secs: 15,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "write-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "write", path: "out.txt", content: "hello", illegal_prop: 1 }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "write-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "write", path: "out.txt" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});

	describe("step-run", () => {
		test("valid minimal", () => {
			const spec: RoutineSpec = {
				name: "run-minimal",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "run", command: "echo hello" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("valid full", () => {
			const spec: RoutineSpec = {
				name: "run-full",
				trigger: [{ manual: {} }],
				steps: [
					{
						id: "step1",
						type: "run",
						command: "npm test",
						cwd: "./app",
						when: "true",
						on_failure: "abort",
						timeout_secs: 60,
					},
				],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(true);
		});

		test("unknown field rejected", () => {
			const spec = {
				name: "run-unknown",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "run", command: "echo hello", unexpected_flag: true }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});

		test("missing required", () => {
			const spec = {
				name: "run-missing",
				trigger: [{ manual: {} }],
				steps: [{ id: "step1", type: "run" }],
			};
			const res = validateRoutineSpec(spec);
			expect(res.valid).toBe(false);
		});
	});
});
